### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by m-doughty**
I thought adding running instructions would be useful. :)

### CODE REVIEW

**Comment by m-doughty** [comment]
Also, if you're interested in making CircleCI work again, feel free to pull from my `config.yml` (I'm not going to make a PR because mine has a bunch of Heroku-specific stuff in):

http://thefineline.io/blog/post/2014/11/08/hablog-on-heroku

**Comment by soupi** [comment]
Thanks! Running instructions sounds like a good idea.

I've decided against maintaining the circle-ci integration as without tests it doesn't give much value, and I'd prefer using gitlab-ci anyway :) But thank you!

I've updated this repo to be up-to-date with the [gitlab repo](https://gitlab.com/gilmi/hablog) as well.

Also note that the link you provided is currently down.

**Comment by m-doughty** [comment]
Oh, yeah I left the date from your sample post on it and updated it: http://thefineline.io/blog/post/2020/09/25/hablog-on-heroku

**Comment by soupi** [comment]
Are you sure it's up? I can't seem to reach thefineline.io at all. I've checked with down.com as well and it seems to be down.

**Pull request merged**
